# Generated by Django 5.1.3 on 2024-11-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="base64image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
