# Generated by Django 5.1.3 on 2024-11-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venue", "0004_venue_lat_venue_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="lat",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
